### ISSUE TITLE
Question around Resizing CIFAR-10

### ISSUE THREAD

**Issue by agneet42** [chs20/RobustVLM#11]
Hi,
Thanks for the great work!
The paper mentions that "evaluate robustness on all datasets at resolution 224x224, except for CIFAR10, CIFAR100 and STL-10", however I find that in the code : https://github.com/chs20/RobustVLM/blob/main/CLIP_eval/clip_robustbench.py#L114, a resize also occurs for CIFAR10. I was wondering what would be the right implementation to consider?

Thanks,
Agneet

**Comment by chs20** [comment]
Hi, 
for these datasets we basically move the resizing into the forward pass: https://github.com/chs20/RobustVLM/blob/87db057dd139d35d5de41f98dd7951ffbad5c0d1/CLIP_eval/clip_robustbench.py#L63
This means that the attack will backpropagate through the resizing and apply perturbations to the images at their original size, i.e. the robustness is evaluated at the original resolution.

**Comment by agneet42** [comment]
Makes sense. Thank you!
