### ISSUE TITLE
Regarding Vision encoder image size for LLaVa-1.5 evaluation

### ISSUE THREAD

**Issue by HashmatShadab** [chs20/RobustVLM#12]
As stated in the paper, ViT-L/14 is used as the CLIP encoder and integrated into the LLaVA-1.5 model, while maintaining the pretrained LLM and projection weights unchanged. However, I am slightly confused because the LLaVA-1.5 model uses ViT-L/14@336 as its vision encoder, and the corresponding projection layers were trained during pretraining and instruction tuning with ViT-L/14@336 as vision backbone. So, the image size should be 336x336 and robust encoder should be aligned with ViT-L/14@336?

**Comment by chs20** [comment]
Hi, yes we use the ViT-L/14@224 with LLaVA. It yields a slight performance drop compared to ViT-L/14@336, but allows us to use the same CLIP model across zero-shot, OpenFlamingo, and LLaVA evaluations. Possibly LLaVA scores could be improved further by training a ViT-L/14@336 FARE model.

**Comment by HashmatShadab** [comment]
Thanks!
