### ISSUE TITLE
CLIP Zero-Shot Reproducing Error

### ISSUE THREAD

**Issue by zaltiner** [chs20/RobustVLM#14]
Hi,
First of all, thank your research. While I was trying to run the baseline code by following the instructions written by you, I am having a lot of errors even though I indicated the path correctly. Whenever I fix one error, I have to debug the rest but I thought the command you shared should be easily runnable without any error.

Can you please explain once again how to run the baseline for CLIP Zero-Shot?
CLIP Zero-Shot
Set models to be evaluated in CLIP_benchmark/benchmark/models.txt and datasets in CLIP_benchmark/benchmark/datasets.txt (the datasets are downloaded from HuggingFace). Then run
cd CLIP_benchmark
./bash/run_benchmark_adv.sh

Regards

**Comment by chs20** [comment]
Hi, which error do you encounter?

**Comment by zaltiner** [comment]
Hi,
Thank you for response.
Currently I made changes on the following 3 file which are run_benchmark_adv.sh, models.txt and cli.py.

The changes I made in run_benchmark_adv.sh file:
	changing SAVE_DIR as --->  SAVE_DIR =~/output
	and adding
		--model_cache_dir /mypath/RobustVLM-main/RobustVLM-main/checkpoint/vitb32_fare_eps_4\
		--pretrained ""

I modifies models.txt as follows
	ViT-B-32,openai
	ViT-B-32,vitb32_fare_eps_4.pt

Finally, I was having error regarding to split(',') in the regarding to models.txt, so I edited the code in cli.py file to check the error. I made changes on def main_eval(base) function to check the error
 	Here is the error I got:
		/mypath/RobustVLM-main/RobustVLM-main/CLIP_benchmark/bash$ bash run_benchmark_adv.sh
		Error: Could not find a pretrained checkpoint for model 'benchmark/models.txt' in the cache directory.
	
The model cannot capture the checkpoint. I appreciate if you can check this problem. Thank you.

**Comment by chs20** [comment]
It seems that it is not recognising `--pretrained_model benchmark/models.txt` as a file, but interprets it as a model name [here](https://github.com/chs20/RobustVLM/blob/7de10ee209f169d415c07aa0abaae4806c402b14/CLIP_benchmark/clip_benchmark/cli.py#L106). Is your working directory `CLIP_benchmark`?

**Comment by zaltiner** [comment]
Yes, that was the reason, thank you for helping!
