### ISSUE TITLE
Adversarial Training FLARE4

### ISSUE THREAD

**Issue by hossainzarif** [chs20/RobustVLM#5]
Hello, while going through your repository, I noticed in your adversarial_training_clip.py  you've only utilized the experiment_name argument for file saving purposes. However, when I attempted to run the file with other experiment_name (such as TECOA4), it ran the same functions as the (FLARE4). Does this repository include all the required modules and functions to execute the unsupervised adversarial training method (i.e., FLARE4)?

**Comment by nmndeep** [comment]
Hi,
Thanks for your interest. 
In the readme, we provide the command to run for TeCoA. ``experiment_name`` is used for logging purposes. The difference between FARE and TeCoA is set implicitly by the ``inner_loss`` arg. As long as you run the command for TeCoA from the Readme - it should work.
Hope this helps.
