### ISSUE TITLE
How do I get the karpathy_coco.json file?

### ISSUE THREAD

**Issue by suiyize** [chs20/RobustVLM#7]
I have to say it's an amazing job。

I noticed a parameter when executing llava_eval.sh
`--coco_karpathy_json_path /mnt/datasets/coco/annotations/karpathy_coco.json`

I want to know` karpathy_coco.json` is how to get, Whether the same as in https://github.com/mehdidc/retrieval_annotations/releases

**Comment by chs20** [comment]
Hi, here are the karpathy annotation files: https://nc.mlcloud.uni-tuebingen.de/index.php/s/mtRnQFaZJkR9zaX
